project_id = "ziiwapwvyavfakeuhvpt"

[functions.cache-demo]
verify_jwt = false

[functions.calculate-loss-bonus]
verify_jwt = true

[functions.claim-loss-bonus]
verify_jwt = true

[functions.sports-proxy]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.process-withdrawal]
verify_jwt = true

[functions.withdraw-request]
verify_jwt = true

[functions.withdraw-approve]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.process-wager-progress]
verify_jwt = true

[functions.deposit-request]
verify_jwt = true

[functions.process-game-session]
verify_jwt = true

[functions.fraud-analysis]
verify_jwt = false

[functions.update-user-risk-profile]
verify_jwt = false

[functions.device-track]
verify_jwt = false