global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'supabase-metrics'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'casino-app'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scheme: https
    tls_config:
      insecure_skip_verify: false

  - job_name: 'edge-functions'
    static_configs:
      - targets: ['ziiwapwvyavfakeuhvpt.supabase.co']
    metrics_path: '/functions/v1/metrics'
    scrape_interval: 60s
    scheme: https
    bearer_token_file: /etc/prometheus/supabase_token

  - job_name: 'uptime-monitoring'
    static_configs:
      - targets: 
          - 'https://ziiwapwvyavfakeuhvpt.supabase.co'
          - 'https://your-casino-domain.com'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115