-- Authentication form çevirilerini ekliyoruz
INSERT INTO public.translations (language_code, namespace, key, value) VALUES
-- Türkçe auth metinleri
('tr', 'auth', 'login_title', 'Giriş Yap'),
('tr', 'auth', 'login_description', 'Hesabınıza giriş yapın'),
('tr', 'auth', 'email_label', 'E-posta Adresi *'),
('tr', 'auth', 'password_label', 'Şifre *'),
('tr', 'auth', 'password_placeholder', 'En az 8 karakter'),
('tr', 'auth', 'email_placeholder', 'ornek@email.com'),
('tr', 'auth', 'captcha_label', 'Güvenlik Doğrulaması *'),
('tr', 'auth', 'captcha_placeholder', 'Sonucu giriniz'),
('tr', 'auth', 'logging_in', 'Giriş yapılıyor...'),
('tr', 'auth', 'login_button', 'Giriş Yap'),
('tr', 'auth', 'forgot_password', 'Şifremi Unuttum'),
('tr', 'auth', 'login_success', 'Giriş Başarılı!'),
('tr', 'auth', 'login_failed', 'Giriş Başarısız'),
('tr', 'auth', 'welcome', 'Hoş geldiniz!'),
('tr', 'auth', 'admin_redirect', 'Admin paneline yönlendiriliyorsunuz...'),

-- Registration metinleri
('tr', 'auth', 'personal_info', 'Kişisel Bilgiler'),
('tr', 'auth', 'account_info', 'Hesap Bilgileri'),
('tr', 'auth', 'address_info', 'Adres Bilgileri'),
('tr', 'auth', 'create_account_desc', 'Hesabınızı oluşturmak için kişisel bilgilerinizi giriniz'),
('tr', 'auth', 'login_info_desc', 'Giriş yapacağınız hesap bilgilerinizi oluşturunuz'),
('tr', 'auth', 'address_desc', 'İkamet adres bilgilerinizi giriniz'),
('tr', 'auth', 'first_name', 'Ad *'),
('tr', 'auth', 'last_name', 'Soyad *'),
('tr', 'auth', 'phone', 'Telefon Numarası *'),
('tr', 'auth', 'birth_date', 'Doğum Tarihi *'),
('tr', 'auth', 'confirm_password', 'Şifre Tekrarı *'),
('tr', 'auth', 'promo_code', 'Promosyon Kodu (Opsiyonel)'),
('tr', 'auth', 'country', 'Ülke *'),
('tr', 'auth', 'city', 'Şehir *'),
('tr', 'auth', 'address', 'Adres *'),
('tr', 'auth', 'postal_code', 'Posta Kodu *'),
('tr', 'auth', 'next', 'İleri'),
('tr', 'auth', 'back', 'Geri'),
('tr', 'auth', 'create_account', 'Hesap Oluştur'),
('tr', 'auth', 'creating_account', 'Hesap oluşturuluyor...'),
('tr', 'auth', 'registration_success', 'Kayıt Başarılı!'),
('tr', 'auth', 'registration_failed', 'Kayıt Başarısız'),
('tr', 'auth', 'check_email', 'Hesabınız başarıyla oluşturuldu. E-posta adresinizi kontrol ediniz.'),
('tr', 'auth', 'welcome_title', 'SportsBet Pro''ya Hoş Geldiniz!'),
('tr', 'auth', 'welcome_desc', 'En iyi bahis deneyimi için hesabınızı oluşturun'),

-- Error messages
('tr', 'auth', 'email_required', 'E-posta zorunludur'),
('tr', 'auth', 'email_invalid', 'Geçerli bir e-posta adresi giriniz'),
('tr', 'auth', 'password_required', 'Şifre zorunludur'),
('tr', 'auth', 'password_min_length', 'Şifre en az 8 karakter olmalıdır'),
('tr', 'auth', 'captcha_required', 'Güvenlik doğrulaması zorunludur'),
('tr', 'auth', 'captcha_wrong', 'Güvenlik doğrulaması yanlış'),
('tr', 'auth', 'name_required', 'Ad zorunludur'),
('tr', 'auth', 'surname_required', 'Soyad zorunludur'),
('tr', 'auth', 'phone_required', 'Telefon numarası zorunludur'),
('tr', 'auth', 'phone_invalid', 'Geçerli bir telefon numarası giriniz (örn: 05xx xxx xx xx)'),
('tr', 'auth', 'birth_date_required', 'Doğum tarihi zorunludur'),
('tr', 'auth', 'age_restriction', '18 yaşından büyük olmalısınız'),
('tr', 'auth', 'passwords_not_match', 'Şifreler eşleşmiyor'),
('tr', 'auth', 'country_required', 'Ülke zorunludur'),
('tr', 'auth', 'city_required', 'Şehir zorunludur'),
('tr', 'auth', 'address_required', 'Adres zorunludur'),
('tr', 'auth', 'postal_code_required', 'Posta kodu zorunludur'),

-- İngilizce auth metinleri
('en', 'auth', 'login_title', 'Login'),
('en', 'auth', 'login_description', 'Sign in to your account'),
('en', 'auth', 'email_label', 'Email Address *'),
('en', 'auth', 'password_label', 'Password *'),
('en', 'auth', 'password_placeholder', 'At least 8 characters'),
('en', 'auth', 'email_placeholder', 'example@email.com'),
('en', 'auth', 'captcha_label', 'Security Verification *'),
('en', 'auth', 'captcha_placeholder', 'Enter the result'),
('en', 'auth', 'logging_in', 'Signing in...'),
('en', 'auth', 'login_button', 'Sign In'),
('en', 'auth', 'forgot_password', 'Forgot Password'),
('en', 'auth', 'login_success', 'Login Successful!'),
('en', 'auth', 'login_failed', 'Login Failed'),
('en', 'auth', 'welcome', 'Welcome!'),
('en', 'auth', 'admin_redirect', 'Redirecting to admin panel...'),

-- Registration metinleri
('en', 'auth', 'personal_info', 'Personal Information'),
('en', 'auth', 'account_info', 'Account Information'),
('en', 'auth', 'address_info', 'Address Information'),
('en', 'auth', 'create_account_desc', 'Enter your personal information to create your account'),
('en', 'auth', 'login_info_desc', 'Create your account credentials for login'),
('en', 'auth', 'address_desc', 'Enter your residential address information'),
('en', 'auth', 'first_name', 'First Name *'),
('en', 'auth', 'last_name', 'Last Name *'),
('en', 'auth', 'phone', 'Phone Number *'),
('en', 'auth', 'birth_date', 'Birth Date *'),
('en', 'auth', 'confirm_password', 'Confirm Password *'),
('en', 'auth', 'promo_code', 'Promo Code (Optional)'),
('en', 'auth', 'country', 'Country *'),
('en', 'auth', 'city', 'City *'),
('en', 'auth', 'address', 'Address *'),
('en', 'auth', 'postal_code', 'Postal Code *'),
('en', 'auth', 'next', 'Next'),
('en', 'auth', 'back', 'Back'),
('en', 'auth', 'create_account', 'Create Account'),
('en', 'auth', 'creating_account', 'Creating account...'),
('en', 'auth', 'registration_success', 'Registration Successful!'),
('en', 'auth', 'registration_failed', 'Registration Failed'),
('en', 'auth', 'check_email', 'Your account has been successfully created. Please check your email.'),
('en', 'auth', 'welcome_title', 'Welcome to SportsBet Pro!'),
('en', 'auth', 'welcome_desc', 'Create your account for the best betting experience'),

-- Error messages
('en', 'auth', 'email_required', 'Email is required'),
('en', 'auth', 'email_invalid', 'Please enter a valid email address'),
('en', 'auth', 'password_required', 'Password is required'),
('en', 'auth', 'password_min_length', 'Password must be at least 8 characters'),
('en', 'auth', 'captcha_required', 'Security verification is required'),
('en', 'auth', 'captcha_wrong', 'Security verification is incorrect'),
('en', 'auth', 'name_required', 'First name is required'),
('en', 'auth', 'surname_required', 'Last name is required'),
('en', 'auth', 'phone_required', 'Phone number is required'),
('en', 'auth', 'phone_invalid', 'Please enter a valid phone number (e.g: 05xx xxx xx xx)'),
('en', 'auth', 'birth_date_required', 'Birth date is required'),
('en', 'auth', 'age_restriction', 'You must be over 18 years old'),
('en', 'auth', 'passwords_not_match', 'Passwords do not match'),
('en', 'auth', 'country_required', 'Country is required'),
('en', 'auth', 'city_required', 'City is required'),
('en', 'auth', 'address_required', 'Address is required'),
('en', 'auth', 'postal_code_required', 'Postal code is required')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET
value = EXCLUDED.value,
updated_at = now();