-- Add missing registration form translations for Step 2 and 3

-- Step 2 - Account Info labels and placeholders
INSERT INTO public.translations (language_code, namespace, key, value) VALUES
('tr', 'auth', 'account_info', 'Hesap Bilgileri'),
('en', 'auth', 'account_info', 'Account Information'),
('tr', 'auth', 'account_info_desc', 'Giriş yapacağınız hesap bilgilerinizi oluşturunuz'),
('en', 'auth', 'account_info_desc', 'Create your login credentials'),
('tr', 'auth', 'email_address', 'E-posta Adresi'),
('en', 'auth', 'email_address', 'Email Address'),
('tr', 'auth', 'email_placeholder', 'ornek@email.com'),
('en', 'auth', 'email_placeholder', 'example@email.com'),
('tr', 'auth', 'password', 'Şifre'),
('en', 'auth', 'password', 'Password'),
('tr', 'auth', 'password_placeholder', 'En az 8 karakter'),
('en', 'auth', 'password_placeholder', 'At least 8 characters'),
('tr', 'auth', 'confirm_password', 'Şifre Tekrarı'),
('en', 'auth', 'confirm_password', 'Confirm Password'),
('tr', 'auth', 'confirm_password_placeholder', 'Şifrenizi tekrar giriniz'),
('en', 'auth', 'confirm_password_placeholder', 'Re-enter your password'),
('tr', 'auth', 'promo_code', 'Promosyon Kodu (Opsiyonel)'),
('en', 'auth', 'promo_code', 'Promo Code (Optional)'),
('tr', 'auth', 'promo_code_placeholder', 'Promosyon kodunuz varsa giriniz'),
('en', 'auth', 'promo_code_placeholder', 'Enter your promo code if you have one'),

-- Step 3 - Address Info labels and placeholders
('tr', 'auth', 'address_info', 'Adres Bilgileri'),
('en', 'auth', 'address_info', 'Address Information'),
('tr', 'auth', 'address_info_desc', 'İkamet adres bilgilerinizi giriniz'),
('en', 'auth', 'address_info_desc', 'Enter your residential address information'),
('tr', 'auth', 'country', 'Ülke'),
('en', 'auth', 'country', 'Country'),
('tr', 'auth', 'country_placeholder', 'Ülke seçiniz'),
('en', 'auth', 'country_placeholder', 'Select country'),
('tr', 'auth', 'city', 'Şehir'),
('en', 'auth', 'city', 'City'),
('tr', 'auth', 'city_placeholder', 'Şehir'),
('en', 'auth', 'city_placeholder', 'City'),
('tr', 'auth', 'address', 'Adres'),
('en', 'auth', 'address', 'Address'),
('tr', 'auth', 'address_placeholder', 'Mahalle, Sokak, Bina No'),
('en', 'auth', 'address_placeholder', 'District, Street, Building No'),
('tr', 'auth', 'postal_code', 'Posta Kodu'),
('en', 'auth', 'postal_code', 'Postal Code'),
('tr', 'auth', 'postal_code_placeholder', '34000'),
('en', 'auth', 'postal_code_placeholder', '34000'),

-- Country options
('tr', 'auth', 'country_turkey', 'Türkiye'),
('en', 'auth', 'country_turkey', 'Turkey'),
('tr', 'auth', 'country_usa', 'Amerika Birleşik Devletleri'),
('en', 'auth', 'country_usa', 'United States'),
('tr', 'auth', 'country_germany', 'Almanya'),
('en', 'auth', 'country_germany', 'Germany'),
('tr', 'auth', 'country_france', 'Fransa'),
('en', 'auth', 'country_france', 'France'),
('tr', 'auth', 'country_uk', 'Birleşik Krallık'),
('en', 'auth', 'country_uk', 'United Kingdom'),

-- Navigation buttons
('tr', 'auth', 'back', 'Geri'),
('en', 'auth', 'back', 'Back'),
('tr', 'auth', 'next', 'İleri'),
('en', 'auth', 'next', 'Next'),
('tr', 'auth', 'saving', 'Kaydediliyor...'),
('en', 'auth', 'saving', 'Saving...'),
('tr', 'auth', 'complete_registration', 'Kaydı Tamamla'),
('en', 'auth', 'complete_registration', 'Complete Registration'),

-- Welcome messages
('tr', 'auth', 'welcome_title', 'SportsBet Pro\'ya Hoş Geldiniz!'),
('en', 'auth', 'welcome_title', 'Welcome to SportsBet Pro!'),
('tr', 'auth', 'welcome_desc', 'En iyi bahis deneyimi için hesabınızı oluşturun'),
('en', 'auth', 'welcome_desc', 'Create your account for the best betting experience'),
('tr', 'auth', 'create_account_mobile', 'Hesap Oluştur'),
('en', 'auth', 'create_account_mobile', 'Create Account'),
('tr', 'auth', 'create_account_mobile_desc', 'En iyi bahis deneyimi için kayıt olun'),
('en', 'auth', 'create_account_mobile_desc', 'Register for the best betting experience');